engines:
  pep8:
    enabled: true
    checks:
      # Line break before binary operator
      W503:
        enabled: false
      # Line break after binary operator
      W504:
        enabled: true
exclude_patterns:
- "animations/"
- "data/"
- "gcn/"
- "graphsage/"
- ".flake8"
