#!/bin/bash
# Stop the Dask cluster on the lip/crunch machines

# Tolerate errors (no "set -x") as we want to loop through all slaves whatever happens

cat dask-slaves | grep -v '^#' | sed 's/ *#.*$//g' | while read slave_nprocs; do
  slave_nprocs=($slave_nprocs)
  slave=${slave_nprocs[0]}
  echo "Stopping slave '$slave'"
  ssh $slave "killall -u slerique dask-worker" < /dev/null
done

echo "All done."
